In [2]:
import pandas as pd

In [5]:
df_books= pd.read_csv("/content/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv",sep=",",header=0)
df_books.head(5)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [7]:
def two_times(value):
  return value*2

In [11]:
df_books["Rating_2"] = df_books["User Rating"].apply(two_times)
df_books.head(5)

,Name,Author,User Rating,Reviews,Price,Year,Genre,Rating_2
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,9.4
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,9.2
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,9.4
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,9.4
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,9.6

In [13]:
df_books["Rating_3"] = df_books["User Rating"].apply(lambda x:x*3)
df_books.head(5)

,Name,Author,User Rating,Reviews,Price,Year,Genre,Rating_2,Rating_3
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,9.4,14.1
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,9.2,13.8
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,9.4,14.1
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,9.4,14.1
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,9.6,14.4

In [19]:
df_books["Rating_4"] = df_books.apply(lambda x:x["User Rating"]*2 if x["Genre"]=="Fiction" else x["User Rating"],axis=1)
df_books

,Name,Author,User Rating,Reviews,Price,Year,Genre,Rating_2,Rating_3,Rating_4
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,9.4,14.1,4.7
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,9.2,13.8,9.2
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,9.4,14.1,4.7
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,9.4,14.1,9.4
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,9.6,14.4,4.8
...,...,...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,9.8,14.7,9.8
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,9.4,14.1,4.7
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,9.4,14.1,4.7
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,9.4,14.1,4.7
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,9.4,14.1,4.7